/* Boxwish Biz CRM — Phases 10-12: Documents, Profile, Dashboard */
(function(){
  const read=k=>{try{return JSON.parse(localStorage.getItem(k)||'[]')}catch{return[]}}, save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt=v=>v?new Date(v).toLocaleString('en-IN',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}):'—';
  const clients=()=>read('boxwishCrmClients'), enquiries=()=>read('boxwishCrmEnquiries');
  const docs=()=>read('boxwishCrmDocuments'), acts=()=>read('boxwishCrmActivities');
  const client=id=>clients().find(x=>x.client_id===id);
  const currentUser=()=>{try{return JSON.parse(sessionStorage.getItem('crmDevUser')||'{}')}catch{return{}}};
  const shell=html=>{if(window.modalShell)return window.modalShell(html);const d=document.createElement('div');d.className='crm-modal';d.innerHTML=`<div class="crm-modal-card">${html}</div>`;document.body.appendChild(d);return d};
  const close=()=>window.closeModal?window.closeModal():document.querySelector('.crm-modal')?.remove();
  const toast=m=>window.showToast&&window.showToast(m);
  function addActivity(type,description,ids={}){let u=currentUser(),a=acts();a.unshift({activity_id:'ACT-'+Date.now(),activity_type:type,description,...ids,performed_by:u.name||'Employee',timestamp:new Date().toISOString()});save('boxwishCrmActivities',a)}
  function docForm(id){let a=docs(),old=a.find(x=>x.document_id===id),d=old||{document_id:'DOC-'+Date.now(),uploaded_at:new Date().toISOString()};let m=shell(`<div class="modal-head"><div><div class="eyebrow">Phase 10 · Documents</div><h2>${old?'Edit Document':'Add Document'}</h2><p>Central document register for enquiries, quotations, FIR, LPA, SAS and orders.</p></div><button class="icon-btn" data-action="p1012-close">×</button></div><form id="docForm" class="form-grid"><div class="form-section"><div class="form-cols"><label>Document Name *<input required name="document_name" value="${esc(d.document_name)}" placeholder="e.g. Client PO"></label><label>Document Type<select name="document_type"><option>Inquiry PDF</option><option>Quotation PDF</option><option>FIR PDF</option><option>LPA PDF</option><option>SAS PDF</option><option>PO Copy</option><option>Invoice</option><option>Delivery Challan</option><option>Product Image</option><option>Logo / Artwork</option><option>Other</option></select></label><label>Client${clientSelect(d.client_id)}</label><label>Enquiry${enquirySelect(d.enquiry_id)}</label><label>File / Drive Reference *<input required name="file_url" value="${esc(d.file_url)}" placeholder="File name or Google Drive link"></label><label>Uploaded By<input name="uploaded_by" value="${esc(d.uploaded_by||currentUser().name||'Employee')}"></label></div><label>Description / Notes<textarea name="notes" rows="3">${esc(d.notes)}</textarea></label></div><div class="modal-actions"><button type="button" class="btn secondary" data-action="p1012-close">Cancel</button><button class="btn primary">${old?'Save Changes':'Add Document'}</button></div></form>`);m.querySelector('[name=document_type]').value=d.document_type||'Other';m.querySelector('#docForm').onsubmit=e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target)),x=docs(),i=x.findIndex(q=>q.document_id===o.document_id);o.updated_at=new Date().toISOString();o.created_at=i>=0?x[i].created_at:o.updated_at;if(i>=0)x[i]=o;else x.unshift(o);save('boxwishCrmDocuments',x);addActivity(i>=0?'Document Updated':'Document Uploaded',o.document_name,{client_id:o.client_id,enquiry_id:o.enquiry_id});close();renderDocs();toast(o.document_name+' saved')}}
  function clientSelect(v){return `<select name="client_id"><option value="">Select client…</option>${clients().map(c=>`<option value="${esc(c.client_id)}" ${c.client_id===v?'selected':''}>${esc(c.company+' — '+c.contact_person)}</option>`).join('')}</select>`}
  function enquirySelect(v){return `<select name="enquiry_id"><option value="">Select enquiry…</option>${enquiries().map(q=>`<option value="${esc(q.enquiry_id)}" ${q.enquiry_id===v?'selected':''}>${esc(q.enquiry_id+' — '+q.company)}</option>`).join('')}</select>`}
  function renderDocs(){let p=document.querySelector('#documents .panel');if(!p)return;p.innerHTML=`<div class="toolbar"><input id="docSearch" placeholder="Search documents, client, enquiry or type…"><select id="docType"><option>All Types</option><option>Inquiry PDF</option><option>Quotation PDF</option><option>FIR PDF</option><option>LPA PDF</option><option>SAS PDF</option><option>PO Copy</option><option>Invoice</option><option>Delivery Challan</option><option>Product Image</option><option>Logo / Artwork</option><option>Other</option></select><button class="btn secondary" data-action="p1012-new-doc">+ Add Document</button></div><div id="docTable"></div>`;let paint=()=>{let q=(document.getElementById('docSearch').value||'').toLowerCase(),t=document.getElementById('docType').value,a=docs().filter(x=>(!q||[x.document_name,x.document_type,x.enquiry_id,client(x.client_id)?.company,x.file_url].join(' ').toLowerCase().includes(q))&&(!t||t==='All Types'||x.document_type===t));document.getElementById('docTable').innerHTML=a.length?`<div class="table-wrap"><table><thead><tr><th>Document</th><th>Type</th><th>Client</th><th>Enquiry</th><th>Uploaded</th><th></th></tr></thead><tbody>${a.map(x=>`<tr><td><strong>${esc(x.document_name)}</strong><br><small>${esc(x.file_url)}</small></td><td>${esc(x.document_type)}</td><td>${esc(client(x.client_id)?.company||'—')}</td><td>${esc(x.enquiry_id||'—')}</td><td>${fmt(x.uploaded_at||x.created_at)}</td><td class="row-actions"><button class="link-btn" data-action="p1012-edit-doc" data-id="${esc(x.document_id)}">Edit</button><button class="link-btn danger" data-action="p1012-delete-doc" data-id="${esc(x.document_id)}">Delete</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="table-empty">No documents registered yet.<br><button class="btn secondary" data-action="p1012-new-doc">Add your first document</button></div>'};paint();document.getElementById('docSearch').oninput=paint;document.getElementById('docType').onchange=paint}
  function renderProfile(){let p=document.querySelector('#profile .panel');if(!p)return;let u=currentUser(),prefs=read('boxwishCrmProfile')[0]||{};p.innerHTML=`<div class="profile-card"><div class="profile-avatar">${esc((u.name||'E').slice(0,1).toUpperCase())}</div><div><div class="eyebrow">Phase 11 · Profile</div><h2>${esc(u.name||'Employee')}</h2><p>Employee ID: <strong>${esc(u.employee_id||u.id||'Not available')}</strong></p></div></div><form id="profileForm" class="form-grid"><div class="form-section"><h3>Salesperson Details</h3><div class="form-cols"><label>Full Name<input name="name" value="${esc(prefs.name||u.name)}" required></label><label>Designation<input name="designation" value="${esc(prefs.designation)}"></label><label>Department<input name="department" value="${esc(prefs.department)}"></label><label>Mobile<input name="mobile" value="${esc(prefs.mobile)}"></label><label>Email<input type="email" name="email" value="${esc(prefs.email)}"></label><label>Employee ID<input readonly value="${esc(u.employee_id||u.id||'')}"></label></div></div><div class="form-section"><h3>Access</h3><p class="muted">Login credentials remain controlled by the CRM authentication layer. This profile page does not store passwords in the browser.</p></div><div class="modal-actions"><button class="btn primary">Save Profile</button></div></form>`;p.querySelector('#profileForm').onsubmit=e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));save('boxwishCrmProfile',[o]);addActivity('Profile Updated','Employee profile updated');toast('Profile saved')}}
  function renderDashboard12(){let d=document.querySelector('#dashboard');if(!d)return;let en=enquiries(),q=read('boxwishCrmQuotations'),f=read('boxwishCrmFIR'),l=read('boxwishCrmLPA'),s=read('boxwishCrmSAS'),o=read('boxwishCrmOrders'),fu=read('boxwishCrmFollowUps'),today=new Date().toISOString().slice(0,10),pipeline=o.reduce((n,x)=>n+Number(x.order_value||0),0),open=en.filter(x=>!['Won','Lost'].includes(x.status)).length,followToday=fu.filter(x=>x.followup_date===today&&x.status!=='Completed').length;let box=document.getElementById('bw12Dashboard');if(!box){box=document.createElement('div');box.id='bw12Dashboard';box.className='dashboard-extra';d.appendChild(box)}box.innerHTML=`<div class="dashboard-extra-head"><div><div class="eyebrow">Phase 12 · Live CRM Snapshot</div><h2>Business Pipeline</h2><p>Live figures from the current CRM data.</p></div></div><div class="dashboard-kpis"><div><strong>${en.length}</strong><span>Total Enquiries</span></div><div><strong>${open}</strong><span>Open Enquiries</span></div><div><strong>${q.length}</strong><span>Quotations</span></div><div><strong>${f.filter(x=>x.internal_approval_status==='Pending'||x.approval_status==='Pending').length}</strong><span>FIR Pending</span></div><div><strong>${l.filter(x=>x.approval_status==='Pending').length}</strong><span>LPA Pending</span></div><div><strong>${s.filter(x=>x.approval_status==='Pending').length}</strong><span>SAS Pending</span></div><div><strong>${o.length}</strong><span>Orders</span></div><div><strong>${money(pipeline)}</strong><span>Order Value</span></div><div><strong>${followToday}</strong><span>Follow Ups Today</span></div></div><div class="dashboard-grid"><div class="dashboard-mini"><h3>Order Lifecycle</h3><p>PO Received: <strong>${o.filter(x=>x.po_received==='Yes').length}</strong></p><p>Production In Progress: <strong>${o.filter(x=>x.production_status==='In Progress').length}</strong></p><p>QC Pending: <strong>${o.filter(x=>x.qc_status==='Pending').length}</strong></p><p>Dispatch Pending: <strong>${o.filter(x=>x.dispatch_status==='Pending').length}</strong></p><p>Payment Pending: <strong>${o.filter(x=>x.payment_status!=='Received').length}</strong></p></div><div class="dashboard-mini"><h3>Recent Activity</h3>${acts().slice(0,6).map(x=>`<p><strong>${esc(x.activity_type)}</strong> — ${esc(x.description)}<br><small>${fmt(x.timestamp)}</small></p>`).join('')||'<p class="muted">No activity yet.</p>'}</div></div>`}
  document.addEventListener('click',e=>{let b=e.target.closest('[data-action]');if(!b)return;let a=b.dataset.action,id=b.dataset.id;if(a==='p1012-close')close();if(a==='p1012-new-doc')docForm();if(a==='p1012-edit-doc')docForm(id);if(a==='p1012-delete-doc'&&confirm('Delete this document record?')){save('boxwishCrmDocuments',docs().filter(x=>x.document_id!==id));renderDocs();toast('Document deleted')}});
  window.renderDocs=renderDocs;window.renderProfile=renderProfile;window.renderDashboard12=renderDashboard12;
  const oldNav=window.navigate;if(oldNav)window.navigate=function(page){oldNav(page);if(page==='documents')renderDocs();if(page==='profile')renderProfile();if(page==='dashboard')renderDashboard12()};
  function money(v){return '₹'+Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2})}
  setTimeout(()=>{renderDashboard12()},100);
})();